# Project information
site_name: Google Noto Fonts docs
site_description: Documentation for the Google Noto fonts project
site_author: The Google Internationalization Team
site_url: https://twardoch.github.io/noto-docs/

# Repository
repo_name: noto-fonts
repo_url: https://github.com/googlei18n/noto-fonts/

# Copyright
copyright: Copyright © 2016 by Google Inc. and contributors

# Documentation and theme
theme: material

# Options
extra:
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Noto Sans
    mono: Noto Mono
  social:
    - type: github-alt
      link: https://github.com/googlei18n

docs_dir: wiki/
site_dir: ../docs/
use_directory_urls: true

# Extensions
markdown_extensions:
  - codehilite:
      css_class: 'code'
  - pymdownx.betterem
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.headeranchor
  - pymdownx.mark
  - smarty
  - attr_list
  - footnotes
  - admonition
  - toc:
      permalink: '#'
  - markdown_include.include:
      'base_path': 'wiki/'
  - mdx_sections
  - figcap
  - mdx_steroids.wikilink

# Page tree
pages:
- index.md
- FAQ.md
- License:
    - License.md
