# Project information
site_name: Google Noto Fonts docs
site_description: Documentation for the Google Noto fonts project
site_author: The Google Internationalization Team
site_url: https://twardoch.github.io/noto-docs/

# Repository
repo_name: noto-mkdocs-theme
repo_url: https://github.com/twardoch/noto-mkdocs-theme

# Copyright
copyright: Copyright © 2016 by Google Inc. and contributors

# Documentation and theme
# theme: noto_mktheme
theme_dir: ../../noto-mkdocs-theme/noto_mktheme/

# Options
extra:
  version: 0.2.5
  logo: images/logo.png
  github:
    download_release: true
  author:
    github: twardoch
    twitter: adamtwar

docs_dir: wiki/
site_dir: ../docs/
use_directory_urls: true

# Extensions
markdown_extensions:
  - codehilite:
      css_class: 'code'
  - pymdownx.betterem
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.headeranchor
  - pymdownx.mark
  - smarty
  - attr_list
  - footnotes
  - admonition
  - toc:
      permalink: '#'
  - markdown_include.include:
      'base_path': 'wiki/'
  - mdx_sections
  - mdx_steroids.figcaption
  - mdx_steroids.wikilink

# Page tree
pages:
- index.md
- FAQ.md
- License:
    - License.md
